-- PROCEDIMIENTO ALMACENADO QUE CONSULTA LA INFORMACIÓN DEL TIPO DE MULTA INDICADO
CREATE PROC sp_Consulta_TipoMulta
(
@IdTipoMulta int
)
AS
BEGIN
	SELECT * 
	FROM TipoMulta 
	WHERE IdTipoMulta = @IdTipoMulta
END